- op: replace
  path: /spec/rules/0/host
  value: www.amidostacks.com

- op: add
  path: /spec/tls
  value:
    - hosts:
      - prod.amidostacks.com
      - www.amidostacks.com

- op: add
  path: /spec/rules/-
  value:
    host: "prod.azure.amidostacks.com"
    http:
      paths:
      - path: /api/menu(/|$)(.*)
        backend:
          serviceName: menuapi
          servicePort: 80


#for localhost prod
- op: add
  path: /spec/rules/-
  value:
    host: "prod.localhost"
    http:
      paths:
      - path: /api/menu(/|$)(.*)
        backend:
          serviceName: menuapi
          servicePort: 80