{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stacks-dotnet.serviceAccountName" . }}
  labels:
    {{- include "stacks-dotnet.labels" . | nindent 4 }}
{{- end }}
