kind: Deployment
apiVersion: apps/v1
metadata:
  name: menuapi
spec:
  template:
    spec:
      containers:
        - name: menuapi
          volumeMounts:
          - name: appsettings
            mountPath: /app/config
      volumes:
        - name: appsettings
          configMap:
            name: appsettings