apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./../../base
resources:
- namespace.yaml
namespace: devx-menu
commonLabels:
  environment: devx
patchesJson6902:
- path: ingress_patch.yaml
  target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: menuapi
patchesStrategicMerge:
- deployment_patch.yaml
configMapGenerator:
- name: appsettings
  files:
    - appsettings.json
secretGenerator:
- name: cosmosdb
  behavior: replace
  files:
  - secrets/cosmosdb/key
- name: appinsights
  behavior: replace
  files:
  - secrets/appinsights/instrumentationkey