- op: replace
  path: /spec/rules/0/host
  value: dev.amidostacks.com

- op: add
  path: /spec/tls
  value:
    - hosts:
      - dev.amidostacks.com

- op: add
  path: /spec/rules/-
  value:
    host: "dev.azure.amidostacks.com"
    http:
      paths:
      - path: /api/menu(/|$)(.*)
        backend:
          serviceName: menuapi
          servicePort: 80
