apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./../../base
resources:
- namespace.yaml
namespace: dev-menu
commonLabels:
  environment: dev
patchesJson6902:
- path: ingress_patch.yaml
  target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: menuapi
patchesStrategicMerge:
- deployment_patch.yaml
configMapGenerator:
- name: appsettings
  files:
    - appsettings.json