# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This application version string will be used to form the name of k8s objects such as configmaps and secrets to support
# This is typically overwritten at deploy time by --set flag when running Helm
applicationVersion: "0.1.0"

replicaCount: 1

image:
  # Default image repository, typically overwritten by --set flag when running Helm
  repository: amidoeunnxgacrnp.azurecr.io/dotnet
  # Default image tag, typically overwritten by --set flag when running Helm
  tag: "latest"
  pullPolicy: IfNotPresent
  # Credentials to pull images from ACR are not required when cluster SPN has Azure RBAC permissions to ACR

application:
 port: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {
    "kubernetes.io/ingress.class": "nginx"
    }
  path: /
  hosts:
    - amido-ref-dotnet-test.k8s.dbw.cloud
    - amido-ref-dotnet-test-eun.k8s.dbw.cloud
    - amido-ref-dotnet-test-euw.k8s.dbw.cloud
  tls: []

# Values for configmap
# These are mapped as environment variables on the deployed application
configMapValues:
  THIS_DOES_NOTHING: test
  SO_DOES_THIS: test

# Tokens for secret references
# These end up mapped as environment variables to the application once deployed
# The values are substituted through CI/CD tooling at deploy time
secretValues:
  username: "#{username}"
  password: "#{password}"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
