apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: menuapi
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /api/menu(/|$)(.*)
        backend:
          serviceName: menuapi
          servicePort: 80