apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
commonLabels:
  app.kubernetes.io/component: api
  app.kubernetes.io/name: menuapi
  app.kubernetes.io/part-of: menu
# environment: dev # applied by overlays for each environment
commonAnnotations:
  role: api
  stage: stable
  tier: frontend
  app.kubernetes.io/instance: manuapi
  app.kubernetes.io/managed-by: kustomize
  projectID: stacks
  applicationName: menu
  applicationId: stacks/menu
  customerID: amido
  owner: amido/dotnet
# CD pipeline annotations
# release: 0.0.1
# version: 2019.06.07-1703 #inserted by CD pipeline
# app.kubernetes.io/version: 2019.06.07-1703
# releasedOn: "2019-06-07T16:42:05Z"
images:
- name: menuapi
  newName: amidostacksacrukstmp.azurecr.io/guibirow/xx-amido-xx.xx-stacks-xx.api
  newTag: 2019.06.10-1819
