apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.applicationVersion }}-secret
type: Opaque
data:
  username: {{ .Values.secretValues.username | b64enc }}
  password: {{ .Values.secretValues.password | b64enc }}